### ISSUE TITLE
Can no longer query UnitDebuff by spell name

### ISSUE THREAD

**Issue by Stmdotcom** [davidmarshall15/Healbot#41]
The global `HEALBOT_DEBUFF_WEAKENED_SOUL` is the spell name, if you look how this is used it can only be a spell ID now (It is used in a UnitDebuff func)

So line 584 in HealBot_Global.lua can be changed to 
`HEALBOT_DEBUFF_WEAKENED_SOUL            = 6788;`

The get for the spell name is un-needed. I'm not sure if this effects the other spell globals for spells in this file, would depend on usage.

You can replicate this issue by casting PWS as a priest (Level 78 shadow) on yourself then ones it times out the error is thrown when Healbot checks for the existence of weakened soul.

**Comment by davidmarshall15** [comment]
This is fixed.
