### ISSUE TITLE
multiple lua error on mouse over 

### ISSUE THREAD

**Issue by zobi** [davidmarshall15/Healbot#45]
Hello, and thanks for healbot ;)

With the new version 8.0.1.8 i have a problem sometimes when i mouse over a friens multiple lua error appear like this :  

`Interface\AddOns\HealBot\HealBot.lua:5504: attempt to compare number with nil
Time: Tue Sep 18 22:01:07 2018
Count: 1134
Stack: Interface\AddOns\HealBot\HealBot.lua:5504: attempt to compare number with nil
[C]: ?
Interface\AddOns\HealBot\HealBot.lua:5504: in function `HealBot_SmartCast'
Interface\AddOns\HealBot\HealBot_Action.lua:4170: in function `HealBot_Action_SmartCast'
Interface\AddOns\HealBot_Tips\HealBot_Tooltip.lua:452: in function <Interface\AddOns\HealBot_Tips\HealBot_Tooltip.lua:407>
Interface\AddOns\HealBot_Tips\HealBot_Tooltip.lua:795: in function `HealBot_Action_RefreshTooltip'
Interface\AddOns\HealBot\HealBot.lua:4281: in function <Interface\AddOns\HealBot\HealBot.lua:4184>
Interface\AddOns\HealBot\HealBot.lua:4311: in function `HealBot_OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>`

Thanks a lot for your job

PS : the website is down :/

**Comment by davidmarshall15** [comment]
Found and fixed in next version, thanks.

**Comment by zobi** [comment]
Thanks a lot ;)
