### ISSUE TITLE
Combat protection broken since 8.0.1.10.

### ISSUE THREAD

**Issue by AnrDaemon** [davidmarshall15/Healbot#48]
Skin defaults for: Solo, Party.
Targets include: Self, Group.
Combat protection: Group, Raid.
Heal groups: MT+Healers+Group.

No reserved bars are shown when solo.
If I'm inviting somebody when in combat, the party members aren't shown until out of combat.

**Comment by davidmarshall15** [comment]
When solo there is no reason to reserve bars, as per the change log, bars are now automatically reserved to match the party or raid size.
